#!/usr/bin/php

<?php

use Smce\Core\SmConsole;

use Smce\SmAutoload;

define('SMCE_PATH',dirname(__FILE__));
define('BASE_PATH',dirname(__FILE__));

require("SmAutoload.php");
$SmAutoload=new SmAutoload;
$SmAutoload->register();

new SmConsole( $_SERVER["argv"]);

