#!/usr/bin/php

<?php

// use SmConsole
use Smce\Core\SmConsole;

// use SmAutoload
use Smce\SmAutoload;

// include app config class
require_once dirname(__FILE__).'/config.php';

// include smce autoload class
require_once $smce_path.'/ConsoleAutoload.php';


// get console
new SmConsole( $_SERVER["argv"]);

